version: '3.8'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile.web
      args:
        - VITE_DEFAULT_EMAIL="test@domain"
        - VITE_HELP_EMAIL=="test@domain"
    restart: always
    ports:
      - 8081:8081
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true