version: '3.8'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile.web
      args:
        - VITE_DEFAULT_EMAIL="noreply@findr.blog"
        - VITE_HELP_EMAIL=="help@findr.blog"
    restart: always
    ports:
      - 8081:8081
    networks:
      - app_network
  web-admin:
    container_name: web-admin
    build:
      context: .
      dockerfile: ./Dockerfile.web-admin
      args:
        - VITE_DEFAULT_EMAIL="noreply@findr.blog"
        - VITE_HELP_EMAIL=="help@findr.blog"
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true