name: Deploy to Railway

on:
    push:
        branches:
            - feat/mono-repo

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push web-admin
              uses: docker/build-push-action@v3
              with:
                  context: ./
                  file: ./apps/web-admin/Dockerfile
                  push: true
                  tags: rontheline/web-admin:latest
                  # build-args: |
                  #     VITE_DEFAULT_EMAIL=${{ secrets.VITE_DEFAULT_EMAIL }}
                  #     VITE_HELP_EMAIL=${{ secrets.VITE_HELP_EMAIL }}

            - name: Build and push web
              uses: docker/build-push-action@v3
              with:
                  context: ./
                  file: ./apps/web/Dockerfile
                  push: true
                  tags: rontheline/web:latest
                  # build-args: |
                  #     VITE_DEFAULT_EMAIL=${{ secrets.VITE_DEFAULT_EMAIL }}
                  #     VITE_HELP_EMAIL=${{ secrets.VITE_HELP_EMAIL }}

            - name: Install Railway CLI
              run: curl -sSL https://railway.app/install.sh | sh
            - name: Set Railway token
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
              run: |
                  # Now Railway CLI will use the token from env var automatically
                  railway whoami

            - name: Set Railway project
              env:
                  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
              run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

            - name: Deploy web-admin to Railway
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
              run: |
                  cd apps/web-admin
                  railway up

            - name: Deploy web to Railway
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
              run: |
                  cd apps/web
                  railway up
